name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: **/*.py